### PR TITLE
Fix for issue #17

### PR DESCRIPTION
**Pull request by c0un7-z3r0**
Created a PR using the solution of @deepsweet to fix Issue #17

### CODE REVIEW

**Comment by deepsweet** [comment]
It should be fixed it 2 places actually, see https://github.com/deepsweet/resize-observer-polyfill/commit/700a38bc6198730ca1e9d95ff952ef5b15eff38a

Didn't have time to create a PR by myself, thanks for taking the initiative.

**Comment by c0un7-z3r0** [comment]
added @deepsweet solution to the other place as well.

@deepsweet Thanks for the hint

**Comment by c0un7-z3r0** [comment]
I guess it has been fixed by @que-etc in commit https://github.com/que-etc/resize-observer-polyfill/commit/10d761da48ab2b32a170c81b134b21ce657e1c7e

**Comment by que-etc** [comment]
@c0un7-z3r0 

Thank you for taking your to make this PR. I really appreciate it.

The reason why I didn't merge is because this fix covers only the `typeof Element` case, while there are cases when we need to access host objects defined in the same context with provided element: https://github.com/que-etc/resize-observer-polyfill/blob/a3ae98bcd34e972b92d9e40e8b974a75399503e8/src/utils/geometry.js#L176
https://github.com/que-etc/resize-observer-polyfill/blob/a3ae98bcd34e972b92d9e40e8b974a75399503e8/src/utils/geometry.js#L88

**Pull request closed without merging**
