### PR TITLE
Build

### PR DESCRIPTION
**Pull request by TrySound**
Tests are still fails, not sure why
Es dist doesn't make sense for bower

### CODE REVIEW

**Comment by TrySound** [comment]
Also `jsnext:main` field is not used anymore.

**Comment by que-etc** [comment]
@TrySound 

Thank you so much for making all these pull requests! I really appreciate it and I'm sorry for making you wait so long (been preoccupied with the ordeal of an immigration process).

As for the build fails, I'll add an extra case for pull requests that will run tests in Firefox instead of connecting to Sauce Labs (#26).

**Comment by TrySound** [comment]
Thanks to you for this project.

**Comment by TrySound** [comment]
Hope to see release with types soon.:)

**Comment by que-etc** [comment]
Working on it right now )

I just wanna ship it with fixes for some of the pending issues. Pretty sure that it will be out today.

**Pull request merged**
